### ISSUE TITLE
Assumptions behind tables?

### ISSUE THREAD

**Issue by bjornbm** [kkazuo/xlsx-tabular#1]
Hi, what are the assumptions on table formatting that need to be fulfilled for xlsx-tabular to work properly? I have a spread sheet for which I had to remove the `takeUntil` processing step (`src/Codec/Xlsx/Util/Tabular.hs` line 114), otherwise getCells would return an empty list. Unfortunately I don't read Japanese so I cannot understand the documentation of `getCells`, `takeContiguous`, and `takeUntil`. Thanks

**Comment by kkazuo** [comment]
Sorry for inconvenience.
I have tried to add English comment on commit 07390c95507775f40fae8d7b0ee12aa8af406829

**Comment by bjornbm** [comment]
Thanks a lot for the update! This is consistent with what I understood the intent to be from inspecting the code.

I have a questions about the assumption:

```
-- |  * no bottom border line means out of table.
```

I understand that you expect every table row will have a bottom border, like so:

```
Header
--------
Row 1
--------
Row 2
--------
```

However, I process tables that do not fulfil this expectation (and they are also not under my control as I receive them from other people). They may look like:

```
Header
--------
Row 1
Row 2
```

Or even:

```
Header
Row 1
Row 2
```

Is the `takeUntil` step based on bottom border important for your uses? As mentioned above, to use your library I had to fork it and remove the `takeUntil` step (relying instead only on the tables being contiguous). Would you be interested in supporting this use case?

**Comment by kkazuo** [comment]
I think there are cultural differences.
In Japan, most of tables in xlsx documents are like this:

```
Some documents here....
---------------------------
| Header1 | Header2 | ... |
---------------------------
| Value1  | Vlaue2  | ... |
---------------------------
| Value1  | Vlaue2  | ... |
---------------------------
Maybe some annoying text here, I don't care about.
```

The meaning value cell has sorounded by borderline.
Then, a simple heuristic filtering just works.

The tables that you show are very rare in Japan.
I feel some foreign open-mindedness from that no-border table style.

Anyway, source forking is very welcome!
Please edit to fit your needs.

It is good that to pluggable the cell traversal stopping strategy.

**Comment by bjornbm** [comment]
Thanks for the explanation. I will probably make a pull request to document what you just explained and that allows users to provide a custom row filtering predicate.
